- hosts: localhost
  
  vars:
    apache_group: 
      Debian: "root" 
      RedHat: "apache"
    apache_ctl: 
      Debian: "/usr/sbin/apache2ctl"
      RedHat: "/usr/sbin/apachectl"

  tasks:
  - yum: pkg={{item}} state=present
    when: ansible_os_family == "RedHat"
    with_items:
    - tar
    - sudo
    - supervisor

  - shell: yum clean all

  - user: name={{item}} group=wheel state=present
    with_items:
    - gcloud
    - ansible

  - pip: name=apache-libcloud

  - get_url: url=https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz dest=/tmp
 
  - unarchive: src=/tmp/google-cloud-sdk.tar.gz dest=/home/gcloud creates=/home/gcloud/google-cloud-sdk copy=no

  - shell: /home/gcloud/google-cloud-sdk/install.sh --usage-reporting false --bash-completion true --rc-path /home/gcloud/.bashrc --path-update true
